---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      profile: auburn
  vars_files:
    - ../var-file.yaml
  vars:
    host:
      - "{{ mydb.endpoint.address }}"
  tasks:
    - name: create image_gallery secret
      aws_secret:
        name: 'm5-pswd-secret'
        state: present
        secret_type: 'string'
        description: password
        secret: " {\"username\":\"{{ user[1] }}\", \"password\":\"{{ password[1] }}\", \"host\":\"{{ host }}\"}"
