---
- hosts: localhost
  gather_facts: yes
  module_defaults:
    group/aws:
      profile: auburn
  tasks:
    - name: Create nginx security group
      ec2_group:
        name: nginx-sg
        description: sg for nginx servers
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on ports 22 and 80
      register: sg_nginx
    - name: create pg security group
      ec2_group:
        name: m5-postgres-sg
        description: allows postgres to serve tagged security groups
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 5432
            rule_desc: allow traffic to postgres from approved groups
      register: pgsg
    - name: create pg tag security group for clients of postgres
      ec2_group:
        name: m5-postgres-tag-sg
        description: allow clients to connect to postgres
        vpc_id: "{{ vpc.vpc.id }}"
        rules_egress:
          - proto: tcp
            ports:
              - 5432
            group_id: "{{ pgsg.group_id }}"
      register: m5pgtag
    - name: update pg security group to allow traffic to postgres from tagged clients
      ec2_group:
        name: m5-postgres-sg
        description: allows postgres to serve tagged security groups
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 5432
            group_id: "{{ m5pgtag.group_id }}"
            rule_desc: allow traffic to postgres from approved groups
